### ISSUE TITLE
Can't make it work under python3.8

### ISSUE THREAD

**Issue by hpiedcoq** [lorenzoromani1983/facebookTranscripts#1]
Hi Lorenzo!

Doesn't seem to work on my computer.
Python 3.8.

`$ python3 facebookTranscripts.py 
Type the object of your research (if needed, between quotes): "Azərbaycan Ermənistanı"

 [*] Searching videos for: "Azərbaycan Ermənistanı" 

 [*] Extracting 309 videos... 

Traceback (most recent call last):
  File "facebookTranscripts.py", line 62, in <module>
    getData()   
  File "facebookTranscripts.py", line 48, in getData
    jsonData = json.loads(data)            
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Any idea?`

**Comment by lorenzoromani1983** [comment]
Hi! I noticed your issue only now. 
I'll look into it asap.
In the meanwhile, did you find any solution?
